name: number_hunter
description: A simple number guessing game - صياد الارقام
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  
  # الفولدر مال الصور والايقونات
  assets:
    - assets/

# اعدادات الايقونة للتطبيق
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21